# Site settings
title: "Net Zero Map VT Demo"
email: mjr@clearbold.com
description: ""
baseurl: ""
url: "http://netzerovt.org"
twitter_username:
github_username:  clearbold

# Where things are
destination:      ./_site
# source:           ./_source


# Handling Reading
exclude:          ["templates", "Gemfile", "Gemfile.lock", "README.md", ".gitignore"]

# Conversion
markdown: kramdown

# Compensating for gh-pages project site
baseurl: /netzerovt
# https://github.com/jekyll/jekyll/issues/332
